site_name: MT FCG User Documentation
nav:
  - Home: index.md
  - Code Generation: code-generation.md
  - User Management: user-management.md
  - Number Management: number-management.md
extra_css: [extra.css]
plugins:
  - search
  - pdf-export:
      combined: true
markdown_extensions:
  - def_list
