name: Build Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install mkdocs
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs mkdocs-pdf-export-plugin
      - name: Build docs
        run: |
          python -m mkdocs build
      - uses: actions/upload-artifact@v2
        whith:
          name: fcg-user-docs
          path: site/
